"""8_updated Order_with_shipmentstatus

Revision ID: 64e0ff6a0a7f
Revises: e190ba6852eb
Create Date: 2025-09-29 17:19:17.338064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64e0ff6a0a7f'
down_revision: Union[str, Sequence[str], None] = 'e190ba6852eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('paypal_order_id', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('shipment_status', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'orders', ['paypal_order_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='unique')
    op.drop_column('orders', 'shipment_status')
    op.drop_column('orders', 'paypal_order_id')
    # ### end Alembic commands ###
