"""5_Pizza_table

Revision ID: 793b76cbe691
Revises: 0d5d6e93f24a
Create Date: 2025-09-27 20:07:09.276115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '793b76cbe691'
down_revision: Union[str, Sequence[str], None] = '0d5d6e93f24a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pizzas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('full_price', sa.Numeric(), nullable=False),
    sa.Column('slice_price', sa.Numeric(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('ingredients', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('pizza_type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pizzas')
    # ### end Alembic commands ###
