"""10_Order_payment_status

Revision ID: 839b1f58782a
Revises: 5a57ac342344
Create Date: 2025-10-01 12:47:25.940638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '839b1f58782a'
down_revision: Union[str, Sequence[str], None] = '5a57ac342344'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'payment_status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
    # ### # 1. Fill existing NULLs
    # ### op.execute("UPDATE orders SET payment_status = 'PENDING' WHERE payment_status IS NULL")
    # 2. Alter column to NOT NULL
    # ### op.alter_column('orders', 'payment_status', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'payment_status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
