"""3_add_type_column_to_pizza

Revision ID: 8e8d7e6cfae0
Revises: 217170681fb2
Create Date: 2025-09-08 22:38:32.957731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8e8d7e6cfae0'
down_revision: Union[str, Sequence[str], None] = '217170681fb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
   """Upgrade schema."""
   # ### commands auto generated by Alembic - please adjust! ###
   # op.drop_table('pizzas')
   # op.drop_table('users')
   op.add_column('pizzas', sa.Column('type', sa.String(), nullable=False, server_default='unknown'))

   # ### end Alembic commands ###

def downgrade() -> None:
   """Downgrade schema."""
   # ### commands auto generated by Alembic - please adjust! ###
   op.create_table('users',
   sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
   sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True),
   sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
   sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True),
   sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
   sa.Column('avatar', sa.VARCHAR(), autoincrement=False, nullable=True),
   sa.Column('provider', sa.VARCHAR(), autoincrement=False, nullable=True),
   sa.Column('provider_id', sa.VARCHAR(), autoincrement=False, nullable=True),
   sa.PrimaryKeyConstraint('id', name=op.f('users_pkey')),
   sa.UniqueConstraint('email', name=op.f('users_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
   sa.UniqueConstraint('username', name=op.f('users_username_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
   )
   op.create_table('pizzas',
   sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
   sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
   sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
   sa.Column('full_price', sa.NUMERIC(), autoincrement=False, nullable=False),
   sa.Column('slice_price', sa.NUMERIC(), autoincrement=False, nullable=False),
   sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=False),
   sa.Column('ingredient_list', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False),
   sa.PrimaryKeyConstraint('id', name=op.f('pizzas_pkey'))
   )
   # ### end Alembic commands ###
